WITH twelve AS (
	SELECT 	DATENAME(MONTH, CONCAT(YEAR(GETDATE()), '-01-01')) AS month,
			DAY(EOMONTH(CONCAT(YEAR(GETDATE()), '-01-01'))) AS day
    UNION
	SELECT 	DATENAME(MONTH, CONCAT(YEAR(GETDATE()), '-02-01')) AS month,
			DAY(EOMONTH(CONCAT(YEAR(GETDATE()), '-02-01'))) AS day
    UNION
	SELECT 	DATENAME(MONTH, CONCAT(YEAR(GETDATE()), '-03-01')) AS month,
			DAY(EOMONTH(CONCAT(YEAR(GETDATE()), '-03-01'))) AS day
    UNION
	SELECT 	DATENAME(MONTH, CONCAT(YEAR(GETDATE()), '-04-01')) AS month,
			DAY(EOMONTH(CONCAT(YEAR(GETDATE()), '-04-01'))) AS day
    UNION
	SELECT 	DATENAME(MONTH, CONCAT(YEAR(GETDATE()), '-05-01')) AS month,
			DAY(EOMONTH(CONCAT(YEAR(GETDATE()), '-05-01'))) AS day
    UNION
	SELECT 	DATENAME(MONTH, CONCAT(YEAR(GETDATE()), '-06-01')) AS month,
			DAY(EOMONTH(CONCAT(YEAR(GETDATE()), '-06-01'))) AS day
    UNION
	SELECT 	DATENAME(MONTH, CONCAT(YEAR(GETDATE()), '-07-01')) AS month,
			DAY(EOMONTH(CONCAT(YEAR(GETDATE()), '-07-01'))) AS day
    UNION
	SELECT 	DATENAME(MONTH, CONCAT(YEAR(GETDATE()), '-08-01')) AS month,
			DAY(EOMONTH(CONCAT(YEAR(GETDATE()), '-08-01'))) AS day
    UNION
	SELECT 	DATENAME(MONTH, CONCAT(YEAR(GETDATE()), '-09-01')) AS month,
			DAY(EOMONTH(CONCAT(YEAR(GETDATE()), '-09-01'))) AS day
    UNION
	SELECT 	DATENAME(MONTH, CONCAT(YEAR(GETDATE()), '-10-01')) AS month,
			DAY(EOMONTH(CONCAT(YEAR(GETDATE()),'-10-01'))) AS day
    UNION
	SELECT 	DATENAME(MONTH, CONCAT(YEAR(GETDATE()), '-11-01')) AS month,
			DAY(EOMONTH(CONCAT(YEAR(GETDATE()), '-11-01'))) AS day
    UNION
	SELECT 	DATENAME(MONTH, CONCAT(YEAR(GETDATE()), '-12-01')) AS month,
			DAY(EOMONTH(CONCAT(YEAR(GETDATE()), '-12-01'))) AS day	
) 
SELECT month, day FROM twelve;